MONGO_DB_HOSTNAME = "127.0.0.1"
MONGO_DB_PORT = 27017

REDIS_HOSTNAME = "127.0.0.1"
REDIS_PORT = 6379

MQTT_HOSTNAME = "127.0.01"

DEVICE_MESSAGES_QUEUE_KEY = "devices_message"


class ACTIONS_TYPES(object):
    RULE_TRIGGERED = "RULE_TRIGGERED"
    CHANGE_VALUE = "CHANGE_VALUE"
